---
label: Product Item
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
  description: Enter title, needs to match filename for routing
- type: file
  name: product_image
  label: product_image
pages:
- content/products/sterling-creek-og.md
- content/products/mimosa.md
- content/products/animal-mints.md
- content/products/orange-cookies.md
- content/products/sugar-cookies.md
- content/products/sour-skittles.md
